### ISSUE TITLE
Seems of interest for PDE solvers

### ISSUE THREAD

**Issue by PetrKryslUCSD** [mewertd2/HalfEdges.jl#1]
Would you consider adding your relevant repos to the survey of PDE packages? 
Thanks,
P

**Comment by mewertd2** [comment]
Absolutely.  These repos are going to be moving probably on Friday to https://github.com/digitaldomain
So would be best to do so early next week to avoid the (awkward?) transition period.  I'll follow up when the transition is finished.

**Comment by PetrKryslUCSD** [comment]
Nice!

**Comment by mewertd2** [comment]
added this one to the list.

https://github.com/JuliaPDE/SurveyofPDEPackages/pull/22
